package flow

import (
	"fmt"
	"strings"

	"github.com/parsabordbar/ctx3/skillwriter"
)

// Skill builds a fact-only skill describing the call graph. name seeds the
// skill name and prose (module base or directory name).
func (g *CallGraph) Skill(name string) skillwriter.Skill {
	if name == "" {
		name = "project"
	}

	desc := fmt.Sprintf(
		"Call graph of the %s codebase: which functions call which, the entry "+
			"points where execution starts, and how packages fan out. Use when asked "+
			"what calls a function, what a function calls, the execution/control flow, "+
			"where the program starts, or how a change ripples through callers.",
		name)

	entryNote := "No entry points were detected."
	if len(g.Entries) > 0 {
		entryNote = "Execution starts at: " + strings.Join(codeList(g.Entries), ", ") + "."
	}

	overview := fmt.Sprintf(
		"Call-graph facts for `%s` (%d functions across %d packages), generated by `ctx3 flow`.\n\n%s\n\n"+
			"Read `packages.md` first — it is the whole system on one page. Drop to "+
			"`callgraph.md` only once you know which function you care about.",
		name, len(g.Nodes), len(g.Packages), entryNote)

	return skillwriter.Skill{
		Name:        name + "-flow",
		Description: desc,
		Overview:    overview,
		References: []skillwriter.Reference{
			{
				Filename: "packages.md",
				When:     "you want to orient: how the system fans out, which packages drive work, which are leaves",
				Content:  RenderPackageFlow(PackageGraph(g, name)),
			},
			{
				Filename: "callgraph.md",
				When:     "you need the full call tree — callers, callees, and traversal order",
				Content:  RenderText(g),
			},
			{
				Filename: "callgraph.mermaid.md",
				When:     "you want to visualize the call graph as a flowchart",
				Content:  RenderMermaid(g),
			},
		},
	}
}

func codeList(items []string) []string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "`" + s + "`"
	}
	return out
}
