package analyzer

import (
	"fmt"
	"sort"
	"strings"

	"github.com/parsabordbar/ctx3/skillwriter"
)

// Skill builds a fact-only progressive-disclosure skill that captures the
// project's shape: file/dir counts, dependency list, language mix, entry
// points and README preview. name seeds the skill name and prose.
//
// This is the always-on orientation skill: what the project is and where it
// starts, loaded before any deeper per-domain skill (deps, flow, symbols).
func (c ProjectContext) Skill(name string) skillwriter.Skill {
	if name == "" {
		name = "project"
	}

	desc := fmt.Sprintf(
		"Project overview of the %s codebase: file and directory counts, the "+
			"dependency list, language mix, entry points and README preview. Use when "+
			"asked what this project is, what it depends on, what languages it uses, or "+
			"where execution starts.",
		name)

	overview := fmt.Sprintf(
		"Orientation facts for `%s` (%d files, %d directories), generated by `ctx3 context`.\n\n"+
			"Read the reference for the dependency list, language percentages, entry points and README.",
		name, c.TotalFiles, c.TotalDirs)

	return skillwriter.Skill{
		Name:        name + "-overview",
		Description: desc,
		Overview:    overview,
		References: []skillwriter.Reference{
			{
				Filename: "overview.md",
				When:     "you need the dependency list, language mix, entry points or README of the project",
				Content:  c.renderOverview(),
			},
		},
	}
}

// renderOverview composes the overview reference body from the context.
func (c ProjectContext) renderOverview() string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# %s — overview\n\n", c.Root)
	fmt.Fprintf(&sb, "- Files: %d\n- Directories: %d\n\n", c.TotalFiles, c.TotalDirs)

	counts := CollectFileStats(&c)
	if pcts := FilePercentage(counts); len(pcts) > 0 {
		sb.WriteString("## Languages\n\n")
		type lang struct {
			ext string
			pct float64
		}
		langs := make([]lang, 0, len(pcts))
		for ext, p := range pcts {
			langs = append(langs, lang{ext, p})
		}
		sort.Slice(langs, func(i, j int) bool { return langs[i].pct > langs[j].pct })
		for _, l := range langs {
			fmt.Fprintf(&sb, "- %s: %.1f%%\n", l.ext, l.pct)
		}
		sb.WriteString("\n")
	}

	if len(c.Dependencies) > 0 {
		fmt.Fprintf(&sb, "## Dependencies (%d)\n\n", len(c.Dependencies))
		for _, d := range c.Dependencies {
			fmt.Fprintf(&sb, "- %s\n", d)
		}
		sb.WriteString("\n")
	}

	var entries []string
	for _, f := range c.Files {
		if f.IsEntryPoint {
			entries = append(entries, f.Path)
		}
	}
	if len(entries) > 0 {
		sb.WriteString("## Entry points\n\n")
		for _, e := range entries {
			fmt.Fprintf(&sb, "- %s\n", e)
		}
		sb.WriteString("\n")
	}

	if strings.TrimSpace(c.Readme) != "" {
		sb.WriteString("## README preview\n\n")
		sb.WriteString(c.Readme)
		sb.WriteString("\n")
	}

	return sb.String()
}
