package symbols

import (
	"fmt"

	"github.com/parsabordbar/ctx3/skillwriter"
)

// Skill builds a fact-only progressive-disclosure skill exposing the symbol
// index: every top-level declaration with its signature and file:line. name
// seeds the skill name and prose (module base or directory name).
//
// The index is the cheapest possible "where does X live" lookup, so the skill
// is what an agent loads before opening files at random.
func (idx *Index) Skill(name string) skillwriter.Skill {
	if name == "" {
		name = "project"
	}

	pkgs := make(map[string]bool)
	for _, s := range idx.Symbols {
		pkgs[s.Package] = true
	}

	desc := fmt.Sprintf(
		"Symbol index of the %s codebase: every top-level type, struct, interface, "+
			"function, method, const and var with its signature and file:line. Use when "+
			"asked where a symbol is defined, what a package exports, the signature of a "+
			"function or method, or to locate code without reading files.",
		name)

	overview := fmt.Sprintf(
		"Symbol facts for `%s` (%d symbols across %d packages), generated by `ctx3 map`.\n\n"+
			"Look a symbol up in the grep reference for a one-line `file:line: signature`; "+
			"use the Markdown reference for a per-package table grouped by kind.",
		name, len(idx.Symbols), len(pkgs))

	return skillwriter.Skill{
		Name:        name + "-symbols",
		Description: desc,
		Overview:    overview,
		References: []skillwriter.Reference{
			{
				Filename: "symbols.md",
				When:     "you need to find where a symbol is defined or what a package exports (one file:line per symbol)",
				Content:  RenderGrep(idx),
			},
			{
				Filename: "symbols.tables.md",
				When:     "you want the full index as per-package tables grouped by kind",
				Content:  RenderMarkdown(idx),
			},
		},
	}
}
