package gitfacts

import (
	"fmt"
	"strings"

	"github.com/parsabordbar/ctx3/skillwriter"
)

// Skill builds a fact-only progressive-disclosure skill describing what the
// repository's history says about the code. name seeds the skill name and prose.
//
// Unlike the other domains this one goes stale fast — it is a snapshot of a
// moving tree — so the overview says so and points at the refresh script rather
// than letting an agent trust a week-old working set.
func (r *Report) Skill(name string) skillwriter.Skill {
	if name == "" {
		name = "project"
	}

	desc := fmt.Sprintf(
		"Repository history of the %s codebase: current branch, uncommitted work in "+
			"progress, recent commits, and the files that change most often. Use when asked "+
			"what is being worked on, what changed recently, which files are hot or risky, "+
			"or who has been touching an area.",
		name)

	var overview strings.Builder
	fmt.Fprintf(&overview,
		"History facts for `%s`, generated by `ctx3 git`.\n\n"+
			"On branch `%s`", name, r.Branch)
	if r.Head != "" {
		fmt.Fprintf(&overview, " at `%s` (%s)", r.Head, r.HeadDate)
	}
	overview.WriteString(".\n\n")

	if len(r.Uncommitted) == 0 {
		overview.WriteString("The working tree was clean when this was generated.\n\n")
	} else {
		fmt.Fprintf(&overview, "**%d uncommitted change(s)** when this was generated.\n\n", len(r.Uncommitted))
	}
	if len(r.Churn) > 0 {
		fmt.Fprintf(&overview, "Hottest file over the last %d commits: `%s` (%d commits).\n\n",
			r.ChurnWindow, r.Churn[0].Path, r.Churn[0].Commits)
	}
	overview.WriteString(
		"These facts are a snapshot and go stale as soon as anyone commits. " +
			"Run `scripts/refresh.sh` before relying on the uncommitted list.")

	return skillwriter.Skill{
		Name:        name + "-history",
		Description: desc,
		Overview:    overview.String(),
		References: []skillwriter.Reference{
			{
				Filename: "history.md",
				When:     "you need the recent commits, the uncommitted working set, or the file churn ranking",
				Content:  RenderMarkdown(r),
			},
		},
	}
}
