package db

import (
	"fmt"
	"strings"

	"github.com/parsabordbar/ctx3/skillwriter"
)

// Skill builds a fact-only progressive-disclosure skill describing the project's
// databases and relational schema. name seeds the skill name; when empty it
// falls back to the project name the report carries. Callers in a bundle pass
// the same name to every domain so the skills read as one family.
func (r *Report) Skill(name string) skillwriter.Skill {
	if name == "" {
		name = r.Project
	}
	names := make([]string, 0, len(r.Engines))
	for _, e := range r.Engines {
		names = append(names, e.Name)
	}
	engineList := "none detected"
	if len(names) > 0 {
		engineList = strings.Join(names, ", ")
	}

	tableCount, relCount := 0, 0
	if r.Schema != nil {
		tableCount, relCount = len(r.Schema.Tables), len(r.Schema.Relations)
	}

	desc := fmt.Sprintf(
		"Database facts for %s: which datastores it uses (%s)%s. Use when asked about the "+
			"database, schema, tables, columns, foreign keys, relations between entities, "+
			"what a query should join on, or which store holds a given piece of data.",
		r.Project, engineList,
		func() string {
			if tableCount == 0 {
				return ""
			}
			return fmt.Sprintf(", plus the %d-table relational schema and its %d foreign-key relations", tableCount, relCount)
		}())

	overview := fmt.Sprintf(
		"Datastore facts for `%s`, generated by `ctx3 db` from files in the repo "+
			"(migrations, schema files, ORM structs) — no live connection.\n\n"+
			"Engines: %s\nTables: %d · Relations: %d",
		r.Project, engineList, tableCount, relCount)

	refs := []skillwriter.Reference{{
		Filename: "databases.md",
		When:     "you need the detected engines, the evidence behind each, and the table/column layout",
		Content:  RenderText(r),
	}}
	if tableCount > 0 {
		refs = append(refs, skillwriter.Reference{
			Filename: "schema.mermaid.md",
			When:     "you want the entity-relationship diagram",
			Content:  RenderMermaid(r),
		})
	}

	return skillwriter.Skill{
		Name:        skillBase(name) + "-db",
		Description: desc,
		Overview:    overview,
		References:  refs,
	}
}

// skillBase normalizes a project name into the kebab-case form skill names require.
func skillBase(name string) string {
	var out []rune
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out = append(out, r)
		case r == '-', r == '_', r == ' ', r == '.':
			if len(out) > 0 && out[len(out)-1] != '-' {
				out = append(out, '-')
			}
		}
	}
	return strings.Trim(string(out), "-")
}
